"""
OR-Tools CP-SAT Schedule — Use Case B
Orizzonte: 2026-12-07 → 2027-01-06 (31 giorni)
Generato da SmartScheduler ortools_builder.py
"""

from ortools.sat.python import cp_model
import json
from datetime import date, timedelta

def solve_schedule():
    model = cp_model.CpModel()

    # ── Parametri ─────────────────────────────────────────────────────────
    all_workers = ['S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'S12', 'S13', 'P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07']
    standard_workers = ['S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'S12', 'S13']
    specialized_workers = ['P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07']

    days = ['2026-12-07', '2026-12-08', '2026-12-09', '2026-12-10', '2026-12-11', '2026-12-12', '2026-12-13', '2026-12-14', '2026-12-15', '2026-12-16', '2026-12-17', '2026-12-18', '2026-12-19', '2026-12-20', '2026-12-21', '2026-12-22', '2026-12-23', '2026-12-24', '2026-12-25', '2026-12-26', '2026-12-27', '2026-12-28', '2026-12-29', '2026-12-30', '2026-12-31', '2027-01-01', '2027-01-02', '2027-01-03', '2027-01-04', '2027-01-05', '2027-01-06']
    n_days = 31
    shifts = ["morning", "afternoon", "night"]
    shift_hours = {"morning": 6, "afternoon": 6, "night": 12}
    shift_units = {"morning": 1, "afternoon": 1, "night": 2}

    # ── Preferenze dei lavoratori (da Stage 1) ────────────────────────────
    # preference_weights[worker_id][shift_type] = penalità (0=preferito, 3=da evitare)
    preference_weights = {}
    unavailable_dates = {}  # worker_id -> set di indici giorno (0-based)
    preferred_rest_day = {}  # worker_id -> weekday (0=Mon..6=Sun), o None
    night_tolerances = {}   # worker_id -> int 0-5 (0=intollerante, 5=molto tollerante)
    holiday_tolerances = {} # worker_id -> int 0-5

    # Worker S01
    preference_weights["S01"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S01"] = 3
    holiday_tolerances["S01"] = 3
    # Worker S02
    preference_weights["S02"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S02"] = 3
    holiday_tolerances["S02"] = 3
    # Worker S03
    preference_weights["S03"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S03"] = 3
    holiday_tolerances["S03"] = 3
    # Worker S04
    preference_weights["S04"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S04"] = 3
    holiday_tolerances["S04"] = 3
    # Worker S05
    preference_weights["S05"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S05"] = 3
    holiday_tolerances["S05"] = 3
    # Worker S06
    preference_weights["S06"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S06"] = 3
    holiday_tolerances["S06"] = 3
    # Worker S07
    preference_weights["S07"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S07"] = 3
    holiday_tolerances["S07"] = 3
    # Worker S08
    preference_weights["S08"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S08"] = 3
    holiday_tolerances["S08"] = 3
    # Worker S09
    preference_weights["S09"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S09"] = 3
    holiday_tolerances["S09"] = 3
    # Worker S10
    preference_weights["S10"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S10"] = 3
    holiday_tolerances["S10"] = 3
    # Worker S11
    preference_weights["S11"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S11"] = 3
    holiday_tolerances["S11"] = 3
    # Worker S12
    preference_weights["S12"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S12"] = 3
    holiday_tolerances["S12"] = 3
    # Worker S13
    preference_weights["S13"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["S13"] = 3
    holiday_tolerances["S13"] = 3
    # Worker P01
    preference_weights["P01"] = {'morning': 3, 'afternoon': 1, 'night': 1}
    night_tolerances["P01"] = 3
    holiday_tolerances["P01"] = 3
    # Worker P02
    preference_weights["P02"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["P02"] = 3
    holiday_tolerances["P02"] = 3
    # Worker P03
    preference_weights["P03"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["P03"] = 3
    holiday_tolerances["P03"] = 3
    # Worker P04
    preference_weights["P04"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["P04"] = 3
    holiday_tolerances["P04"] = 3
    # Worker P05
    preference_weights["P05"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["P05"] = 3
    holiday_tolerances["P05"] = 3
    # Worker P06
    preference_weights["P06"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["P06"] = 3
    holiday_tolerances["P06"] = 3
    # Worker P07
    preference_weights["P07"] = {'morning': 1, 'afternoon': 1, 'night': 2}
    night_tolerances["P07"] = 3
    holiday_tolerances["P07"] = 3

    # ── Variabili booleane ────────────────────────────────────────────────
    # shift_vars[(worker, day_idx, shift)] = 1 se worker copre quel turno
    shift_vars = {}
    for w in all_workers:
        for d in range(n_days):
            for s in shifts:
                shift_vars[(w, d, s)] = model.NewBoolVar(f"shift_{w}_d{d}_{s}")

    # ========== VINCOLI HARD ==============================================

    # 1. Copertura minima per turno
    for d in range(n_days):
        for s in shifts:
            # Almeno 3 lavoratori totali (specializzati possono coprire ruoli standard)
            model.Add(sum(shift_vars[(w, d, s)] for w in all_workers) >= 3)
            # Almeno 1 specializzato sempre presente
            model.Add(sum(shift_vars[(w, d, s)] for w in specialized_workers) >= 1)

    # 2. Max 1 turno al giorno per lavoratore
    for w in all_workers:
        for d in range(n_days):
            model.Add(sum(shift_vars[(w, d, s)] for s in shifts) <= 1)

    # 3. No turni consecutivi: notte[d] + mattino[d+1] <= 1
    #    (ridondante con vincolo 5, mantenuto per esplicitezza)
    for w in all_workers:
        for d in range(n_days - 1):
            model.Add(shift_vars[(w, d, "night")] + shift_vars[(w, d+1, "morning")] <= 1)

    # 4. Indisponibilità assoluta dei lavoratori (da preferenze)
    for w, unavail_days in unavailable_dates.items():
        for d in unavail_days:
            if 0 <= d < n_days:
                for s in shifts:
                    model.Add(shift_vars[(w, d, s)] == 0)

    # 5. 2 giorni liberi obbligatori dopo ogni turno notturno
    for w in all_workers:
        for d in range(n_days):
            if d + 1 < n_days:
                model.Add(
                    shift_vars[(w, d, "night")] +
                    sum(shift_vars[(w, d+1, s)] for s in shifts) <= 1
                )
            if d + 2 < n_days:
                model.Add(
                    shift_vars[(w, d, "night")] +
                    sum(shift_vars[(w, d+2, s)] for s in shifts) <= 1
                )

    # 6. Max 36 ore in qualsiasi finestra scorrevole di 7 giorni
    window_size = 7
    for w in all_workers:
        for start in range(n_days - window_size + 1):
            window = range(start, start + window_size)
            model.Add(
                sum(shift_vars[(w, d, s)] * shift_hours[s]
                    for d in window for s in shifts) <= 36
            )

    # 7. Esattamente 25 shift-units per lavoratore nel mese
    for w in all_workers:
        model.Add(
            sum(shift_vars[(w, d, s)] * shift_units[s]
                for d in range(n_days) for s in shifts) == 25
        )

    # NOTA: Il bilanciamento dei turni notturni è gestito come VINCOLO SOFT
    # tramite le penaltà in preference_weights (generate da preferences_agent.py).
    # Le penaltà sono proporzionali alla night_tolerance di ogni worker:
    # tolerance 0 → night penalty=5, tolerance 5 → night penalty=0.
    # Un vincolo hard causerebbe INFEASIBLE (capacità max < notti richieste).

    # ========== VINCOLI SOFT (OBIETTIVO) ==================================
    # L'obiettivo minimizza la somma pesata delle penalità sulle preferenze.

    penalty_terms = []

    # Penalità per turni non preferiti (da preference_weights)
    for w in all_workers:
        w_prefs = preference_weights.get(w, {})
        for d in range(n_days):
            for s in shifts:
                pen = w_prefs.get(s, 1)  # 0=preferito, 1=neutro, 3=da evitare
                if pen > 0:
                    penalty_terms.append(shift_vars[(w, d, s)] * pen)

    # Penalità giorno di riposo preferito (IMPLEMENTATA NEL TEMPLATE)
    # Per ogni worker con preferred_rest_day, penalizza i turni nel suo giorno preferito
    for w in all_workers:
        prd = preferred_rest_day.get(w)
        if prd is None:
            continue
        for d in range(n_days):
            if date.fromisoformat(days[d]).weekday() == prd:
                for s in shifts:
                    penalty_terms.append(shift_vars[(w, d, s)] * 2)

    # Penalità turni festivi (IMPLEMENTATA NEL TEMPLATE)
    # Festività: 8 Dicembre, 25-26 Dicembre, 1 Gennaio, 6 Gennaio (per Use Case A e B)
    # Penalità = max(0, 5 - holiday_tolerance) -> da evitare fortemente se tolleranza 0
    holiday_dates = {"2026-12-08", "2026-12-25", "2026-12-26", "2027-01-01", "2027-01-06"}
    for w in all_workers:
        htol = holiday_tolerances.get(w, 3)
        hpen = max(0, 5 - htol)
        if hpen > 0:
            for d in range(n_days):
                if days[d] in holiday_dates:
                    for s in shifts:
                        penalty_terms.append(shift_vars[(w, d, s)] * hpen)

    # ========== ASSEGNAZIONI FISSE (PER FIX-AND-OPTIMIZE LNS) =============
    # Vincoli hard: LNS Freeze
    model.Add(shift_vars[('S11', 0, 'morning')] == 0)
    model.Add(shift_vars[('S11', 0, 'afternoon')] == 1)
    model.Add(shift_vars[('S11', 0, 'night')] == 0)
    model.Add(shift_vars[('S11', 1, 'morning')] == 0)
    model.Add(shift_vars[('S11', 1, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 1, 'night')] == 0)
    model.Add(shift_vars[('S11', 2, 'morning')] == 0)
    model.Add(shift_vars[('S11', 2, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 2, 'night')] == 1)
    model.Add(shift_vars[('S11', 3, 'morning')] == 0)
    model.Add(shift_vars[('S11', 3, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 3, 'night')] == 0)
    model.Add(shift_vars[('S11', 4, 'morning')] == 0)
    model.Add(shift_vars[('S11', 4, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 4, 'night')] == 0)
    model.Add(shift_vars[('S11', 5, 'morning')] == 0)
    model.Add(shift_vars[('S11', 5, 'afternoon')] == 1)
    model.Add(shift_vars[('S11', 5, 'night')] == 0)
    model.Add(shift_vars[('S11', 6, 'morning')] == 0)
    model.Add(shift_vars[('S11', 6, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 6, 'night')] == 1)
    model.Add(shift_vars[('S11', 7, 'morning')] == 0)
    model.Add(shift_vars[('S11', 7, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 7, 'night')] == 0)
    model.Add(shift_vars[('S11', 8, 'morning')] == 0)
    model.Add(shift_vars[('S11', 8, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 8, 'night')] == 0)
    model.Add(shift_vars[('S11', 9, 'morning')] == 0)
    model.Add(shift_vars[('S11', 9, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 9, 'night')] == 1)
    model.Add(shift_vars[('S11', 10, 'morning')] == 0)
    model.Add(shift_vars[('S11', 10, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 10, 'night')] == 0)
    model.Add(shift_vars[('S11', 11, 'morning')] == 0)
    model.Add(shift_vars[('S11', 11, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 11, 'night')] == 0)
    model.Add(shift_vars[('S11', 12, 'morning')] == 0)
    model.Add(shift_vars[('S11', 12, 'afternoon')] == 1)
    model.Add(shift_vars[('S11', 12, 'night')] == 0)
    model.Add(shift_vars[('S11', 13, 'morning')] == 0)
    model.Add(shift_vars[('S11', 13, 'afternoon')] == 1)
    model.Add(shift_vars[('S11', 13, 'night')] == 0)
    model.Add(shift_vars[('S11', 14, 'morning')] == 1)
    model.Add(shift_vars[('S11', 14, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 14, 'night')] == 0)
    model.Add(shift_vars[('S11', 15, 'morning')] == 0)
    model.Add(shift_vars[('S11', 15, 'afternoon')] == 1)
    model.Add(shift_vars[('S11', 15, 'night')] == 0)
    model.Add(shift_vars[('S11', 16, 'morning')] == 0)
    model.Add(shift_vars[('S11', 16, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 16, 'night')] == 1)
    model.Add(shift_vars[('S11', 17, 'morning')] == 0)
    model.Add(shift_vars[('S11', 17, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 17, 'night')] == 0)
    model.Add(shift_vars[('S11', 18, 'morning')] == 0)
    model.Add(shift_vars[('S11', 18, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 18, 'night')] == 0)
    model.Add(shift_vars[('S11', 19, 'morning')] == 0)
    model.Add(shift_vars[('S11', 19, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 19, 'night')] == 0)
    model.Add(shift_vars[('S11', 20, 'morning')] == 0)
    model.Add(shift_vars[('S11', 20, 'afternoon')] == 1)
    model.Add(shift_vars[('S11', 20, 'night')] == 0)
    model.Add(shift_vars[('S11', 21, 'morning')] == 0)
    model.Add(shift_vars[('S11', 21, 'afternoon')] == 1)
    model.Add(shift_vars[('S11', 21, 'night')] == 0)
    model.Add(shift_vars[('S11', 22, 'morning')] == 0)
    model.Add(shift_vars[('S11', 22, 'afternoon')] == 1)
    model.Add(shift_vars[('S11', 22, 'night')] == 0)
    model.Add(shift_vars[('S11', 23, 'morning')] == 0)
    model.Add(shift_vars[('S11', 23, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 23, 'night')] == 1)
    model.Add(shift_vars[('S11', 24, 'morning')] == 0)
    model.Add(shift_vars[('S11', 24, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 24, 'night')] == 0)
    model.Add(shift_vars[('S11', 25, 'morning')] == 0)
    model.Add(shift_vars[('S11', 25, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 25, 'night')] == 0)
    model.Add(shift_vars[('S11', 26, 'morning')] == 1)
    model.Add(shift_vars[('S11', 26, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 26, 'night')] == 0)
    model.Add(shift_vars[('S11', 27, 'morning')] == 0)
    model.Add(shift_vars[('S11', 27, 'afternoon')] == 1)
    model.Add(shift_vars[('S11', 27, 'night')] == 0)
    model.Add(shift_vars[('S11', 28, 'morning')] == 0)
    model.Add(shift_vars[('S11', 28, 'afternoon')] == 1)
    model.Add(shift_vars[('S11', 28, 'night')] == 0)
    model.Add(shift_vars[('S11', 29, 'morning')] == 0)
    model.Add(shift_vars[('S11', 29, 'afternoon')] == 1)
    model.Add(shift_vars[('S11', 29, 'night')] == 0)
    model.Add(shift_vars[('S11', 30, 'morning')] == 0)
    model.Add(shift_vars[('S11', 30, 'afternoon')] == 0)
    model.Add(shift_vars[('S11', 30, 'night')] == 1)
    model.Add(shift_vars[('P04', 0, 'morning')] == 0)
    model.Add(shift_vars[('P04', 0, 'afternoon')] == 1)
    model.Add(shift_vars[('P04', 0, 'night')] == 0)
    model.Add(shift_vars[('P04', 1, 'morning')] == 1)
    model.Add(shift_vars[('P04', 1, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 1, 'night')] == 0)
    model.Add(shift_vars[('P04', 2, 'morning')] == 1)
    model.Add(shift_vars[('P04', 2, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 2, 'night')] == 0)
    model.Add(shift_vars[('P04', 3, 'morning')] == 0)
    model.Add(shift_vars[('P04', 3, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 3, 'night')] == 1)
    model.Add(shift_vars[('P04', 4, 'morning')] == 0)
    model.Add(shift_vars[('P04', 4, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 4, 'night')] == 0)
    model.Add(shift_vars[('P04', 5, 'morning')] == 0)
    model.Add(shift_vars[('P04', 5, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 5, 'night')] == 0)
    model.Add(shift_vars[('P04', 6, 'morning')] == 1)
    model.Add(shift_vars[('P04', 6, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 6, 'night')] == 0)
    model.Add(shift_vars[('P04', 7, 'morning')] == 1)
    model.Add(shift_vars[('P04', 7, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 7, 'night')] == 0)
    model.Add(shift_vars[('P04', 8, 'morning')] == 0)
    model.Add(shift_vars[('P04', 8, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 8, 'night')] == 0)
    model.Add(shift_vars[('P04', 9, 'morning')] == 0)
    model.Add(shift_vars[('P04', 9, 'afternoon')] == 1)
    model.Add(shift_vars[('P04', 9, 'night')] == 0)
    model.Add(shift_vars[('P04', 10, 'morning')] == 0)
    model.Add(shift_vars[('P04', 10, 'afternoon')] == 1)
    model.Add(shift_vars[('P04', 10, 'night')] == 0)
    model.Add(shift_vars[('P04', 11, 'morning')] == 0)
    model.Add(shift_vars[('P04', 11, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 11, 'night')] == 0)
    model.Add(shift_vars[('P04', 12, 'morning')] == 1)
    model.Add(shift_vars[('P04', 12, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 12, 'night')] == 0)
    model.Add(shift_vars[('P04', 13, 'morning')] == 1)
    model.Add(shift_vars[('P04', 13, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 13, 'night')] == 0)
    model.Add(shift_vars[('P04', 14, 'morning')] == 0)
    model.Add(shift_vars[('P04', 14, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 14, 'night')] == 1)
    model.Add(shift_vars[('P04', 15, 'morning')] == 0)
    model.Add(shift_vars[('P04', 15, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 15, 'night')] == 0)
    model.Add(shift_vars[('P04', 16, 'morning')] == 0)
    model.Add(shift_vars[('P04', 16, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 16, 'night')] == 0)
    model.Add(shift_vars[('P04', 17, 'morning')] == 0)
    model.Add(shift_vars[('P04', 17, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 17, 'night')] == 1)
    model.Add(shift_vars[('P04', 18, 'morning')] == 0)
    model.Add(shift_vars[('P04', 18, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 18, 'night')] == 0)
    model.Add(shift_vars[('P04', 19, 'morning')] == 0)
    model.Add(shift_vars[('P04', 19, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 19, 'night')] == 0)
    model.Add(shift_vars[('P04', 20, 'morning')] == 0)
    model.Add(shift_vars[('P04', 20, 'afternoon')] == 1)
    model.Add(shift_vars[('P04', 20, 'night')] == 0)
    model.Add(shift_vars[('P04', 21, 'morning')] == 1)
    model.Add(shift_vars[('P04', 21, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 21, 'night')] == 0)
    model.Add(shift_vars[('P04', 22, 'morning')] == 0)
    model.Add(shift_vars[('P04', 22, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 22, 'night')] == 1)
    model.Add(shift_vars[('P04', 23, 'morning')] == 0)
    model.Add(shift_vars[('P04', 23, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 23, 'night')] == 0)
    model.Add(shift_vars[('P04', 24, 'morning')] == 0)
    model.Add(shift_vars[('P04', 24, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 24, 'night')] == 0)
    model.Add(shift_vars[('P04', 25, 'morning')] == 1)
    model.Add(shift_vars[('P04', 25, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 25, 'night')] == 0)
    model.Add(shift_vars[('P04', 26, 'morning')] == 0)
    model.Add(shift_vars[('P04', 26, 'afternoon')] == 1)
    model.Add(shift_vars[('P04', 26, 'night')] == 0)
    model.Add(shift_vars[('P04', 27, 'morning')] == 1)
    model.Add(shift_vars[('P04', 27, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 27, 'night')] == 0)
    model.Add(shift_vars[('P04', 28, 'morning')] == 0)
    model.Add(shift_vars[('P04', 28, 'afternoon')] == 1)
    model.Add(shift_vars[('P04', 28, 'night')] == 0)
    model.Add(shift_vars[('P04', 29, 'morning')] == 0)
    model.Add(shift_vars[('P04', 29, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 29, 'night')] == 1)
    model.Add(shift_vars[('P04', 30, 'morning')] == 0)
    model.Add(shift_vars[('P04', 30, 'afternoon')] == 0)
    model.Add(shift_vars[('P04', 30, 'night')] == 0)
    model.Add(shift_vars[('P05', 0, 'morning')] == 1)
    model.Add(shift_vars[('P05', 0, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 0, 'night')] == 0)
    model.Add(shift_vars[('P05', 1, 'morning')] == 0)
    model.Add(shift_vars[('P05', 1, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 1, 'night')] == 0)
    model.Add(shift_vars[('P05', 2, 'morning')] == 0)
    model.Add(shift_vars[('P05', 2, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 2, 'night')] == 1)
    model.Add(shift_vars[('P05', 3, 'morning')] == 0)
    model.Add(shift_vars[('P05', 3, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 3, 'night')] == 0)
    model.Add(shift_vars[('P05', 4, 'morning')] == 0)
    model.Add(shift_vars[('P05', 4, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 4, 'night')] == 0)
    model.Add(shift_vars[('P05', 5, 'morning')] == 0)
    model.Add(shift_vars[('P05', 5, 'afternoon')] == 1)
    model.Add(shift_vars[('P05', 5, 'night')] == 0)
    model.Add(shift_vars[('P05', 6, 'morning')] == 1)
    model.Add(shift_vars[('P05', 6, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 6, 'night')] == 0)
    model.Add(shift_vars[('P05', 7, 'morning')] == 1)
    model.Add(shift_vars[('P05', 7, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 7, 'night')] == 0)
    model.Add(shift_vars[('P05', 8, 'morning')] == 1)
    model.Add(shift_vars[('P05', 8, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 8, 'night')] == 0)
    model.Add(shift_vars[('P05', 9, 'morning')] == 0)
    model.Add(shift_vars[('P05', 9, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 9, 'night')] == 1)
    model.Add(shift_vars[('P05', 10, 'morning')] == 0)
    model.Add(shift_vars[('P05', 10, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 10, 'night')] == 0)
    model.Add(shift_vars[('P05', 11, 'morning')] == 0)
    model.Add(shift_vars[('P05', 11, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 11, 'night')] == 0)
    model.Add(shift_vars[('P05', 12, 'morning')] == 0)
    model.Add(shift_vars[('P05', 12, 'afternoon')] == 1)
    model.Add(shift_vars[('P05', 12, 'night')] == 0)
    model.Add(shift_vars[('P05', 13, 'morning')] == 1)
    model.Add(shift_vars[('P05', 13, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 13, 'night')] == 0)
    model.Add(shift_vars[('P05', 14, 'morning')] == 0)
    model.Add(shift_vars[('P05', 14, 'afternoon')] == 1)
    model.Add(shift_vars[('P05', 14, 'night')] == 0)
    model.Add(shift_vars[('P05', 15, 'morning')] == 0)
    model.Add(shift_vars[('P05', 15, 'afternoon')] == 1)
    model.Add(shift_vars[('P05', 15, 'night')] == 0)
    model.Add(shift_vars[('P05', 16, 'morning')] == 0)
    model.Add(shift_vars[('P05', 16, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 16, 'night')] == 1)
    model.Add(shift_vars[('P05', 17, 'morning')] == 0)
    model.Add(shift_vars[('P05', 17, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 17, 'night')] == 0)
    model.Add(shift_vars[('P05', 18, 'morning')] == 0)
    model.Add(shift_vars[('P05', 18, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 18, 'night')] == 0)
    model.Add(shift_vars[('P05', 19, 'morning')] == 1)
    model.Add(shift_vars[('P05', 19, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 19, 'night')] == 0)
    model.Add(shift_vars[('P05', 20, 'morning')] == 0)
    model.Add(shift_vars[('P05', 20, 'afternoon')] == 1)
    model.Add(shift_vars[('P05', 20, 'night')] == 0)
    model.Add(shift_vars[('P05', 21, 'morning')] == 0)
    model.Add(shift_vars[('P05', 21, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 21, 'night')] == 0)
    model.Add(shift_vars[('P05', 22, 'morning')] == 0)
    model.Add(shift_vars[('P05', 22, 'afternoon')] == 1)
    model.Add(shift_vars[('P05', 22, 'night')] == 0)
    model.Add(shift_vars[('P05', 23, 'morning')] == 1)
    model.Add(shift_vars[('P05', 23, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 23, 'night')] == 0)
    model.Add(shift_vars[('P05', 24, 'morning')] == 1)
    model.Add(shift_vars[('P05', 24, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 24, 'night')] == 0)
    model.Add(shift_vars[('P05', 25, 'morning')] == 0)
    model.Add(shift_vars[('P05', 25, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 25, 'night')] == 0)
    model.Add(shift_vars[('P05', 26, 'morning')] == 0)
    model.Add(shift_vars[('P05', 26, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 26, 'night')] == 1)
    model.Add(shift_vars[('P05', 27, 'morning')] == 0)
    model.Add(shift_vars[('P05', 27, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 27, 'night')] == 0)
    model.Add(shift_vars[('P05', 28, 'morning')] == 0)
    model.Add(shift_vars[('P05', 28, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 28, 'night')] == 0)
    model.Add(shift_vars[('P05', 29, 'morning')] == 1)
    model.Add(shift_vars[('P05', 29, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 29, 'night')] == 0)
    model.Add(shift_vars[('P05', 30, 'morning')] == 0)
    model.Add(shift_vars[('P05', 30, 'afternoon')] == 0)
    model.Add(shift_vars[('P05', 30, 'night')] == 1)
    model.Add(shift_vars[('S03', 0, 'morning')] == 1)
    model.Add(shift_vars[('S03', 0, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 0, 'night')] == 0)
    model.Add(shift_vars[('S03', 1, 'morning')] == 0)
    model.Add(shift_vars[('S03', 1, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 1, 'night')] == 0)
    model.Add(shift_vars[('S03', 2, 'morning')] == 0)
    model.Add(shift_vars[('S03', 2, 'afternoon')] == 1)
    model.Add(shift_vars[('S03', 2, 'night')] == 0)
    model.Add(shift_vars[('S03', 3, 'morning')] == 1)
    model.Add(shift_vars[('S03', 3, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 3, 'night')] == 0)
    model.Add(shift_vars[('S03', 4, 'morning')] == 0)
    model.Add(shift_vars[('S03', 4, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 4, 'night')] == 1)
    model.Add(shift_vars[('S03', 5, 'morning')] == 0)
    model.Add(shift_vars[('S03', 5, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 5, 'night')] == 0)
    model.Add(shift_vars[('S03', 6, 'morning')] == 0)
    model.Add(shift_vars[('S03', 6, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 6, 'night')] == 0)
    model.Add(shift_vars[('S03', 7, 'morning')] == 0)
    model.Add(shift_vars[('S03', 7, 'afternoon')] == 1)
    model.Add(shift_vars[('S03', 7, 'night')] == 0)
    model.Add(shift_vars[('S03', 8, 'morning')] == 1)
    model.Add(shift_vars[('S03', 8, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 8, 'night')] == 0)
    model.Add(shift_vars[('S03', 9, 'morning')] == 1)
    model.Add(shift_vars[('S03', 9, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 9, 'night')] == 0)
    model.Add(shift_vars[('S03', 10, 'morning')] == 1)
    model.Add(shift_vars[('S03', 10, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 10, 'night')] == 0)
    model.Add(shift_vars[('S03', 11, 'morning')] == 0)
    model.Add(shift_vars[('S03', 11, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 11, 'night')] == 1)
    model.Add(shift_vars[('S03', 12, 'morning')] == 0)
    model.Add(shift_vars[('S03', 12, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 12, 'night')] == 0)
    model.Add(shift_vars[('S03', 13, 'morning')] == 0)
    model.Add(shift_vars[('S03', 13, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 13, 'night')] == 0)
    model.Add(shift_vars[('S03', 14, 'morning')] == 0)
    model.Add(shift_vars[('S03', 14, 'afternoon')] == 1)
    model.Add(shift_vars[('S03', 14, 'night')] == 0)
    model.Add(shift_vars[('S03', 15, 'morning')] == 1)
    model.Add(shift_vars[('S03', 15, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 15, 'night')] == 0)
    model.Add(shift_vars[('S03', 16, 'morning')] == 0)
    model.Add(shift_vars[('S03', 16, 'afternoon')] == 1)
    model.Add(shift_vars[('S03', 16, 'night')] == 0)
    model.Add(shift_vars[('S03', 17, 'morning')] == 0)
    model.Add(shift_vars[('S03', 17, 'afternoon')] == 1)
    model.Add(shift_vars[('S03', 17, 'night')] == 0)
    model.Add(shift_vars[('S03', 18, 'morning')] == 0)
    model.Add(shift_vars[('S03', 18, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 18, 'night')] == 0)
    model.Add(shift_vars[('S03', 19, 'morning')] == 0)
    model.Add(shift_vars[('S03', 19, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 19, 'night')] == 1)
    model.Add(shift_vars[('S03', 20, 'morning')] == 0)
    model.Add(shift_vars[('S03', 20, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 20, 'night')] == 0)
    model.Add(shift_vars[('S03', 21, 'morning')] == 0)
    model.Add(shift_vars[('S03', 21, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 21, 'night')] == 0)
    model.Add(shift_vars[('S03', 22, 'morning')] == 1)
    model.Add(shift_vars[('S03', 22, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 22, 'night')] == 0)
    model.Add(shift_vars[('S03', 23, 'morning')] == 0)
    model.Add(shift_vars[('S03', 23, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 23, 'night')] == 1)
    model.Add(shift_vars[('S03', 24, 'morning')] == 0)
    model.Add(shift_vars[('S03', 24, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 24, 'night')] == 0)
    model.Add(shift_vars[('S03', 25, 'morning')] == 0)
    model.Add(shift_vars[('S03', 25, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 25, 'night')] == 0)
    model.Add(shift_vars[('S03', 26, 'morning')] == 1)
    model.Add(shift_vars[('S03', 26, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 26, 'night')] == 0)
    model.Add(shift_vars[('S03', 27, 'morning')] == 0)
    model.Add(shift_vars[('S03', 27, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 27, 'night')] == 1)
    model.Add(shift_vars[('S03', 28, 'morning')] == 0)
    model.Add(shift_vars[('S03', 28, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 28, 'night')] == 0)
    model.Add(shift_vars[('S03', 29, 'morning')] == 0)
    model.Add(shift_vars[('S03', 29, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 29, 'night')] == 0)
    model.Add(shift_vars[('S03', 30, 'morning')] == 0)
    model.Add(shift_vars[('S03', 30, 'afternoon')] == 0)
    model.Add(shift_vars[('S03', 30, 'night')] == 1)
    model.Add(shift_vars[('S13', 0, 'morning')] == 0)
    model.Add(shift_vars[('S13', 0, 'afternoon')] == 1)
    model.Add(shift_vars[('S13', 0, 'night')] == 0)
    model.Add(shift_vars[('S13', 1, 'morning')] == 0)
    model.Add(shift_vars[('S13', 1, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 1, 'night')] == 0)
    model.Add(shift_vars[('S13', 2, 'morning')] == 0)
    model.Add(shift_vars[('S13', 2, 'afternoon')] == 1)
    model.Add(shift_vars[('S13', 2, 'night')] == 0)
    model.Add(shift_vars[('S13', 3, 'morning')] == 0)
    model.Add(shift_vars[('S13', 3, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 3, 'night')] == 0)
    model.Add(shift_vars[('S13', 4, 'morning')] == 0)
    model.Add(shift_vars[('S13', 4, 'afternoon')] == 1)
    model.Add(shift_vars[('S13', 4, 'night')] == 0)
    model.Add(shift_vars[('S13', 5, 'morning')] == 0)
    model.Add(shift_vars[('S13', 5, 'afternoon')] == 1)
    model.Add(shift_vars[('S13', 5, 'night')] == 0)
    model.Add(shift_vars[('S13', 6, 'morning')] == 0)
    model.Add(shift_vars[('S13', 6, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 6, 'night')] == 1)
    model.Add(shift_vars[('S13', 7, 'morning')] == 0)
    model.Add(shift_vars[('S13', 7, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 7, 'night')] == 0)
    model.Add(shift_vars[('S13', 8, 'morning')] == 0)
    model.Add(shift_vars[('S13', 8, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 8, 'night')] == 0)
    model.Add(shift_vars[('S13', 9, 'morning')] == 1)
    model.Add(shift_vars[('S13', 9, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 9, 'night')] == 0)
    model.Add(shift_vars[('S13', 10, 'morning')] == 1)
    model.Add(shift_vars[('S13', 10, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 10, 'night')] == 0)
    model.Add(shift_vars[('S13', 11, 'morning')] == 0)
    model.Add(shift_vars[('S13', 11, 'afternoon')] == 1)
    model.Add(shift_vars[('S13', 11, 'night')] == 0)
    model.Add(shift_vars[('S13', 12, 'morning')] == 0)
    model.Add(shift_vars[('S13', 12, 'afternoon')] == 1)
    model.Add(shift_vars[('S13', 12, 'night')] == 0)
    model.Add(shift_vars[('S13', 13, 'morning')] == 0)
    model.Add(shift_vars[('S13', 13, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 13, 'night')] == 1)
    model.Add(shift_vars[('S13', 14, 'morning')] == 0)
    model.Add(shift_vars[('S13', 14, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 14, 'night')] == 0)
    model.Add(shift_vars[('S13', 15, 'morning')] == 0)
    model.Add(shift_vars[('S13', 15, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 15, 'night')] == 0)
    model.Add(shift_vars[('S13', 16, 'morning')] == 0)
    model.Add(shift_vars[('S13', 16, 'afternoon')] == 1)
    model.Add(shift_vars[('S13', 16, 'night')] == 0)
    model.Add(shift_vars[('S13', 17, 'morning')] == 0)
    model.Add(shift_vars[('S13', 17, 'afternoon')] == 1)
    model.Add(shift_vars[('S13', 17, 'night')] == 0)
    model.Add(shift_vars[('S13', 18, 'morning')] == 1)
    model.Add(shift_vars[('S13', 18, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 18, 'night')] == 0)
    model.Add(shift_vars[('S13', 19, 'morning')] == 1)
    model.Add(shift_vars[('S13', 19, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 19, 'night')] == 0)
    model.Add(shift_vars[('S13', 20, 'morning')] == 0)
    model.Add(shift_vars[('S13', 20, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 20, 'night')] == 1)
    model.Add(shift_vars[('S13', 21, 'morning')] == 0)
    model.Add(shift_vars[('S13', 21, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 21, 'night')] == 0)
    model.Add(shift_vars[('S13', 22, 'morning')] == 0)
    model.Add(shift_vars[('S13', 22, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 22, 'night')] == 0)
    model.Add(shift_vars[('S13', 23, 'morning')] == 1)
    model.Add(shift_vars[('S13', 23, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 23, 'night')] == 0)
    model.Add(shift_vars[('S13', 24, 'morning')] == 0)
    model.Add(shift_vars[('S13', 24, 'afternoon')] == 1)
    model.Add(shift_vars[('S13', 24, 'night')] == 0)
    model.Add(shift_vars[('S13', 25, 'morning')] == 1)
    model.Add(shift_vars[('S13', 25, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 25, 'night')] == 0)
    model.Add(shift_vars[('S13', 26, 'morning')] == 0)
    model.Add(shift_vars[('S13', 26, 'afternoon')] == 1)
    model.Add(shift_vars[('S13', 26, 'night')] == 0)
    model.Add(shift_vars[('S13', 27, 'morning')] == 0)
    model.Add(shift_vars[('S13', 27, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 27, 'night')] == 1)
    model.Add(shift_vars[('S13', 28, 'morning')] == 0)
    model.Add(shift_vars[('S13', 28, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 28, 'night')] == 0)
    model.Add(shift_vars[('S13', 29, 'morning')] == 0)
    model.Add(shift_vars[('S13', 29, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 29, 'night')] == 0)
    model.Add(shift_vars[('S13', 30, 'morning')] == 1)
    model.Add(shift_vars[('S13', 30, 'afternoon')] == 0)
    model.Add(shift_vars[('S13', 30, 'night')] == 0)
    model.Add(shift_vars[('P02', 0, 'morning')] == 0)
    model.Add(shift_vars[('P02', 0, 'afternoon')] == 1)
    model.Add(shift_vars[('P02', 0, 'night')] == 0)
    model.Add(shift_vars[('P02', 1, 'morning')] == 0)
    model.Add(shift_vars[('P02', 1, 'afternoon')] == 1)
    model.Add(shift_vars[('P02', 1, 'night')] == 0)
    model.Add(shift_vars[('P02', 2, 'morning')] == 1)
    model.Add(shift_vars[('P02', 2, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 2, 'night')] == 0)
    model.Add(shift_vars[('P02', 3, 'morning')] == 0)
    model.Add(shift_vars[('P02', 3, 'afternoon')] == 1)
    model.Add(shift_vars[('P02', 3, 'night')] == 0)
    model.Add(shift_vars[('P02', 4, 'morning')] == 0)
    model.Add(shift_vars[('P02', 4, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 4, 'night')] == 1)
    model.Add(shift_vars[('P02', 5, 'morning')] == 0)
    model.Add(shift_vars[('P02', 5, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 5, 'night')] == 0)
    model.Add(shift_vars[('P02', 6, 'morning')] == 0)
    model.Add(shift_vars[('P02', 6, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 6, 'night')] == 0)
    model.Add(shift_vars[('P02', 7, 'morning')] == 0)
    model.Add(shift_vars[('P02', 7, 'afternoon')] == 1)
    model.Add(shift_vars[('P02', 7, 'night')] == 0)
    model.Add(shift_vars[('P02', 8, 'morning')] == 0)
    model.Add(shift_vars[('P02', 8, 'afternoon')] == 1)
    model.Add(shift_vars[('P02', 8, 'night')] == 0)
    model.Add(shift_vars[('P02', 9, 'morning')] == 0)
    model.Add(shift_vars[('P02', 9, 'afternoon')] == 1)
    model.Add(shift_vars[('P02', 9, 'night')] == 0)
    model.Add(shift_vars[('P02', 10, 'morning')] == 1)
    model.Add(shift_vars[('P02', 10, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 10, 'night')] == 0)
    model.Add(shift_vars[('P02', 11, 'morning')] == 0)
    model.Add(shift_vars[('P02', 11, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 11, 'night')] == 1)
    model.Add(shift_vars[('P02', 12, 'morning')] == 0)
    model.Add(shift_vars[('P02', 12, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 12, 'night')] == 0)
    model.Add(shift_vars[('P02', 13, 'morning')] == 0)
    model.Add(shift_vars[('P02', 13, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 13, 'night')] == 0)
    model.Add(shift_vars[('P02', 14, 'morning')] == 0)
    model.Add(shift_vars[('P02', 14, 'afternoon')] == 1)
    model.Add(shift_vars[('P02', 14, 'night')] == 0)
    model.Add(shift_vars[('P02', 15, 'morning')] == 0)
    model.Add(shift_vars[('P02', 15, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 15, 'night')] == 0)
    model.Add(shift_vars[('P02', 16, 'morning')] == 1)
    model.Add(shift_vars[('P02', 16, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 16, 'night')] == 0)
    model.Add(shift_vars[('P02', 17, 'morning')] == 1)
    model.Add(shift_vars[('P02', 17, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 17, 'night')] == 0)
    model.Add(shift_vars[('P02', 18, 'morning')] == 0)
    model.Add(shift_vars[('P02', 18, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 18, 'night')] == 1)
    model.Add(shift_vars[('P02', 19, 'morning')] == 0)
    model.Add(shift_vars[('P02', 19, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 19, 'night')] == 0)
    model.Add(shift_vars[('P02', 20, 'morning')] == 0)
    model.Add(shift_vars[('P02', 20, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 20, 'night')] == 0)
    model.Add(shift_vars[('P02', 21, 'morning')] == 0)
    model.Add(shift_vars[('P02', 21, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 21, 'night')] == 1)
    model.Add(shift_vars[('P02', 22, 'morning')] == 0)
    model.Add(shift_vars[('P02', 22, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 22, 'night')] == 0)
    model.Add(shift_vars[('P02', 23, 'morning')] == 0)
    model.Add(shift_vars[('P02', 23, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 23, 'night')] == 0)
    model.Add(shift_vars[('P02', 24, 'morning')] == 1)
    model.Add(shift_vars[('P02', 24, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 24, 'night')] == 0)
    model.Add(shift_vars[('P02', 25, 'morning')] == 0)
    model.Add(shift_vars[('P02', 25, 'afternoon')] == 1)
    model.Add(shift_vars[('P02', 25, 'night')] == 0)
    model.Add(shift_vars[('P02', 26, 'morning')] == 0)
    model.Add(shift_vars[('P02', 26, 'afternoon')] == 1)
    model.Add(shift_vars[('P02', 26, 'night')] == 0)
    model.Add(shift_vars[('P02', 27, 'morning')] == 0)
    model.Add(shift_vars[('P02', 27, 'afternoon')] == 1)
    model.Add(shift_vars[('P02', 27, 'night')] == 0)
    model.Add(shift_vars[('P02', 28, 'morning')] == 0)
    model.Add(shift_vars[('P02', 28, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 28, 'night')] == 1)
    model.Add(shift_vars[('P02', 29, 'morning')] == 0)
    model.Add(shift_vars[('P02', 29, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 29, 'night')] == 0)
    model.Add(shift_vars[('P02', 30, 'morning')] == 0)
    model.Add(shift_vars[('P02', 30, 'afternoon')] == 0)
    model.Add(shift_vars[('P02', 30, 'night')] == 0)
    model.Add(shift_vars[('P06', 0, 'morning')] == 1)
    model.Add(shift_vars[('P06', 0, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 0, 'night')] == 0)
    model.Add(shift_vars[('P06', 1, 'morning')] == 0)
    model.Add(shift_vars[('P06', 1, 'afternoon')] == 1)
    model.Add(shift_vars[('P06', 1, 'night')] == 0)
    model.Add(shift_vars[('P06', 2, 'morning')] == 0)
    model.Add(shift_vars[('P06', 2, 'afternoon')] == 1)
    model.Add(shift_vars[('P06', 2, 'night')] == 0)
    model.Add(shift_vars[('P06', 3, 'morning')] == 1)
    model.Add(shift_vars[('P06', 3, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 3, 'night')] == 0)
    model.Add(shift_vars[('P06', 4, 'morning')] == 0)
    model.Add(shift_vars[('P06', 4, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 4, 'night')] == 1)
    model.Add(shift_vars[('P06', 5, 'morning')] == 0)
    model.Add(shift_vars[('P06', 5, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 5, 'night')] == 0)
    model.Add(shift_vars[('P06', 6, 'morning')] == 0)
    model.Add(shift_vars[('P06', 6, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 6, 'night')] == 0)
    model.Add(shift_vars[('P06', 7, 'morning')] == 0)
    model.Add(shift_vars[('P06', 7, 'afternoon')] == 1)
    model.Add(shift_vars[('P06', 7, 'night')] == 0)
    model.Add(shift_vars[('P06', 8, 'morning')] == 1)
    model.Add(shift_vars[('P06', 8, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 8, 'night')] == 0)
    model.Add(shift_vars[('P06', 9, 'morning')] == 0)
    model.Add(shift_vars[('P06', 9, 'afternoon')] == 1)
    model.Add(shift_vars[('P06', 9, 'night')] == 0)
    model.Add(shift_vars[('P06', 10, 'morning')] == 0)
    model.Add(shift_vars[('P06', 10, 'afternoon')] == 1)
    model.Add(shift_vars[('P06', 10, 'night')] == 0)
    model.Add(shift_vars[('P06', 11, 'morning')] == 0)
    model.Add(shift_vars[('P06', 11, 'afternoon')] == 1)
    model.Add(shift_vars[('P06', 11, 'night')] == 0)
    model.Add(shift_vars[('P06', 12, 'morning')] == 1)
    model.Add(shift_vars[('P06', 12, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 12, 'night')] == 0)
    model.Add(shift_vars[('P06', 13, 'morning')] == 0)
    model.Add(shift_vars[('P06', 13, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 13, 'night')] == 0)
    model.Add(shift_vars[('P06', 14, 'morning')] == 0)
    model.Add(shift_vars[('P06', 14, 'afternoon')] == 1)
    model.Add(shift_vars[('P06', 14, 'night')] == 0)
    model.Add(shift_vars[('P06', 15, 'morning')] == 0)
    model.Add(shift_vars[('P06', 15, 'afternoon')] == 1)
    model.Add(shift_vars[('P06', 15, 'night')] == 0)
    model.Add(shift_vars[('P06', 16, 'morning')] == 0)
    model.Add(shift_vars[('P06', 16, 'afternoon')] == 1)
    model.Add(shift_vars[('P06', 16, 'night')] == 0)
    model.Add(shift_vars[('P06', 17, 'morning')] == 0)
    model.Add(shift_vars[('P06', 17, 'afternoon')] == 1)
    model.Add(shift_vars[('P06', 17, 'night')] == 0)
    model.Add(shift_vars[('P06', 18, 'morning')] == 0)
    model.Add(shift_vars[('P06', 18, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 18, 'night')] == 0)
    model.Add(shift_vars[('P06', 19, 'morning')] == 0)
    model.Add(shift_vars[('P06', 19, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 19, 'night')] == 1)
    model.Add(shift_vars[('P06', 20, 'morning')] == 0)
    model.Add(shift_vars[('P06', 20, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 20, 'night')] == 0)
    model.Add(shift_vars[('P06', 21, 'morning')] == 0)
    model.Add(shift_vars[('P06', 21, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 21, 'night')] == 0)
    model.Add(shift_vars[('P06', 22, 'morning')] == 0)
    model.Add(shift_vars[('P06', 22, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 22, 'night')] == 1)
    model.Add(shift_vars[('P06', 23, 'morning')] == 0)
    model.Add(shift_vars[('P06', 23, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 23, 'night')] == 0)
    model.Add(shift_vars[('P06', 24, 'morning')] == 0)
    model.Add(shift_vars[('P06', 24, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 24, 'night')] == 0)
    model.Add(shift_vars[('P06', 25, 'morning')] == 0)
    model.Add(shift_vars[('P06', 25, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 25, 'night')] == 1)
    model.Add(shift_vars[('P06', 26, 'morning')] == 0)
    model.Add(shift_vars[('P06', 26, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 26, 'night')] == 0)
    model.Add(shift_vars[('P06', 27, 'morning')] == 0)
    model.Add(shift_vars[('P06', 27, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 27, 'night')] == 0)
    model.Add(shift_vars[('P06', 28, 'morning')] == 1)
    model.Add(shift_vars[('P06', 28, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 28, 'night')] == 0)
    model.Add(shift_vars[('P06', 29, 'morning')] == 0)
    model.Add(shift_vars[('P06', 29, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 29, 'night')] == 1)
    model.Add(shift_vars[('P06', 30, 'morning')] == 0)
    model.Add(shift_vars[('P06', 30, 'afternoon')] == 0)
    model.Add(shift_vars[('P06', 30, 'night')] == 0)
    model.Add(shift_vars[('S09', 0, 'morning')] == 1)
    model.Add(shift_vars[('S09', 0, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 0, 'night')] == 0)
    model.Add(shift_vars[('S09', 1, 'morning')] == 0)
    model.Add(shift_vars[('S09', 1, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 1, 'night')] == 1)
    model.Add(shift_vars[('S09', 2, 'morning')] == 0)
    model.Add(shift_vars[('S09', 2, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 2, 'night')] == 0)
    model.Add(shift_vars[('S09', 3, 'morning')] == 0)
    model.Add(shift_vars[('S09', 3, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 3, 'night')] == 0)
    model.Add(shift_vars[('S09', 4, 'morning')] == 0)
    model.Add(shift_vars[('S09', 4, 'afternoon')] == 1)
    model.Add(shift_vars[('S09', 4, 'night')] == 0)
    model.Add(shift_vars[('S09', 5, 'morning')] == 1)
    model.Add(shift_vars[('S09', 5, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 5, 'night')] == 0)
    model.Add(shift_vars[('S09', 6, 'morning')] == 1)
    model.Add(shift_vars[('S09', 6, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 6, 'night')] == 0)
    model.Add(shift_vars[('S09', 7, 'morning')] == 1)
    model.Add(shift_vars[('S09', 7, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 7, 'night')] == 0)
    model.Add(shift_vars[('S09', 8, 'morning')] == 0)
    model.Add(shift_vars[('S09', 8, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 8, 'night')] == 1)
    model.Add(shift_vars[('S09', 9, 'morning')] == 0)
    model.Add(shift_vars[('S09', 9, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 9, 'night')] == 0)
    model.Add(shift_vars[('S09', 10, 'morning')] == 0)
    model.Add(shift_vars[('S09', 10, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 10, 'night')] == 0)
    model.Add(shift_vars[('S09', 11, 'morning')] == 0)
    model.Add(shift_vars[('S09', 11, 'afternoon')] == 1)
    model.Add(shift_vars[('S09', 11, 'night')] == 0)
    model.Add(shift_vars[('S09', 12, 'morning')] == 0)
    model.Add(shift_vars[('S09', 12, 'afternoon')] == 1)
    model.Add(shift_vars[('S09', 12, 'night')] == 0)
    model.Add(shift_vars[('S09', 13, 'morning')] == 1)
    model.Add(shift_vars[('S09', 13, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 13, 'night')] == 0)
    model.Add(shift_vars[('S09', 14, 'morning')] == 1)
    model.Add(shift_vars[('S09', 14, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 14, 'night')] == 0)
    model.Add(shift_vars[('S09', 15, 'morning')] == 0)
    model.Add(shift_vars[('S09', 15, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 15, 'night')] == 1)
    model.Add(shift_vars[('S09', 16, 'morning')] == 0)
    model.Add(shift_vars[('S09', 16, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 16, 'night')] == 0)
    model.Add(shift_vars[('S09', 17, 'morning')] == 0)
    model.Add(shift_vars[('S09', 17, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 17, 'night')] == 0)
    model.Add(shift_vars[('S09', 18, 'morning')] == 1)
    model.Add(shift_vars[('S09', 18, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 18, 'night')] == 0)
    model.Add(shift_vars[('S09', 19, 'morning')] == 0)
    model.Add(shift_vars[('S09', 19, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 19, 'night')] == 0)
    model.Add(shift_vars[('S09', 20, 'morning')] == 1)
    model.Add(shift_vars[('S09', 20, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 20, 'night')] == 0)
    model.Add(shift_vars[('S09', 21, 'morning')] == 0)
    model.Add(shift_vars[('S09', 21, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 21, 'night')] == 1)
    model.Add(shift_vars[('S09', 22, 'morning')] == 0)
    model.Add(shift_vars[('S09', 22, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 22, 'night')] == 0)
    model.Add(shift_vars[('S09', 23, 'morning')] == 0)
    model.Add(shift_vars[('S09', 23, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 23, 'night')] == 0)
    model.Add(shift_vars[('S09', 24, 'morning')] == 1)
    model.Add(shift_vars[('S09', 24, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 24, 'night')] == 0)
    model.Add(shift_vars[('S09', 25, 'morning')] == 0)
    model.Add(shift_vars[('S09', 25, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 25, 'night')] == 1)
    model.Add(shift_vars[('S09', 26, 'morning')] == 0)
    model.Add(shift_vars[('S09', 26, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 26, 'night')] == 0)
    model.Add(shift_vars[('S09', 27, 'morning')] == 0)
    model.Add(shift_vars[('S09', 27, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 27, 'night')] == 0)
    model.Add(shift_vars[('S09', 28, 'morning')] == 0)
    model.Add(shift_vars[('S09', 28, 'afternoon')] == 1)
    model.Add(shift_vars[('S09', 28, 'night')] == 0)
    model.Add(shift_vars[('S09', 29, 'morning')] == 1)
    model.Add(shift_vars[('S09', 29, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 29, 'night')] == 0)
    model.Add(shift_vars[('S09', 30, 'morning')] == 1)
    model.Add(shift_vars[('S09', 30, 'afternoon')] == 0)
    model.Add(shift_vars[('S09', 30, 'night')] == 0)
    model.Add(shift_vars[('S12', 0, 'morning')] == 1)
    model.Add(shift_vars[('S12', 0, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 0, 'night')] == 0)
    model.Add(shift_vars[('S12', 1, 'morning')] == 0)
    model.Add(shift_vars[('S12', 1, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 1, 'night')] == 1)
    model.Add(shift_vars[('S12', 2, 'morning')] == 0)
    model.Add(shift_vars[('S12', 2, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 2, 'night')] == 0)
    model.Add(shift_vars[('S12', 3, 'morning')] == 0)
    model.Add(shift_vars[('S12', 3, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 3, 'night')] == 0)
    model.Add(shift_vars[('S12', 4, 'morning')] == 0)
    model.Add(shift_vars[('S12', 4, 'afternoon')] == 1)
    model.Add(shift_vars[('S12', 4, 'night')] == 0)
    model.Add(shift_vars[('S12', 5, 'morning')] == 0)
    model.Add(shift_vars[('S12', 5, 'afternoon')] == 1)
    model.Add(shift_vars[('S12', 5, 'night')] == 0)
    model.Add(shift_vars[('S12', 6, 'morning')] == 1)
    model.Add(shift_vars[('S12', 6, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 6, 'night')] == 0)
    model.Add(shift_vars[('S12', 7, 'morning')] == 1)
    model.Add(shift_vars[('S12', 7, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 7, 'night')] == 0)
    model.Add(shift_vars[('S12', 8, 'morning')] == 0)
    model.Add(shift_vars[('S12', 8, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 8, 'night')] == 1)
    model.Add(shift_vars[('S12', 9, 'morning')] == 0)
    model.Add(shift_vars[('S12', 9, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 9, 'night')] == 0)
    model.Add(shift_vars[('S12', 10, 'morning')] == 0)
    model.Add(shift_vars[('S12', 10, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 10, 'night')] == 0)
    model.Add(shift_vars[('S12', 11, 'morning')] == 1)
    model.Add(shift_vars[('S12', 11, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 11, 'night')] == 0)
    model.Add(shift_vars[('S12', 12, 'morning')] == 0)
    model.Add(shift_vars[('S12', 12, 'afternoon')] == 1)
    model.Add(shift_vars[('S12', 12, 'night')] == 0)
    model.Add(shift_vars[('S12', 13, 'morning')] == 0)
    model.Add(shift_vars[('S12', 13, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 13, 'night')] == 0)
    model.Add(shift_vars[('S12', 14, 'morning')] == 0)
    model.Add(shift_vars[('S12', 14, 'afternoon')] == 1)
    model.Add(shift_vars[('S12', 14, 'night')] == 0)
    model.Add(shift_vars[('S12', 15, 'morning')] == 0)
    model.Add(shift_vars[('S12', 15, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 15, 'night')] == 1)
    model.Add(shift_vars[('S12', 16, 'morning')] == 0)
    model.Add(shift_vars[('S12', 16, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 16, 'night')] == 0)
    model.Add(shift_vars[('S12', 17, 'morning')] == 0)
    model.Add(shift_vars[('S12', 17, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 17, 'night')] == 0)
    model.Add(shift_vars[('S12', 18, 'morning')] == 0)
    model.Add(shift_vars[('S12', 18, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 18, 'night')] == 1)
    model.Add(shift_vars[('S12', 19, 'morning')] == 0)
    model.Add(shift_vars[('S12', 19, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 19, 'night')] == 0)
    model.Add(shift_vars[('S12', 20, 'morning')] == 0)
    model.Add(shift_vars[('S12', 20, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 20, 'night')] == 0)
    model.Add(shift_vars[('S12', 21, 'morning')] == 0)
    model.Add(shift_vars[('S12', 21, 'afternoon')] == 1)
    model.Add(shift_vars[('S12', 21, 'night')] == 0)
    model.Add(shift_vars[('S12', 22, 'morning')] == 0)
    model.Add(shift_vars[('S12', 22, 'afternoon')] == 1)
    model.Add(shift_vars[('S12', 22, 'night')] == 0)
    model.Add(shift_vars[('S12', 23, 'morning')] == 1)
    model.Add(shift_vars[('S12', 23, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 23, 'night')] == 0)
    model.Add(shift_vars[('S12', 24, 'morning')] == 0)
    model.Add(shift_vars[('S12', 24, 'afternoon')] == 1)
    model.Add(shift_vars[('S12', 24, 'night')] == 0)
    model.Add(shift_vars[('S12', 25, 'morning')] == 0)
    model.Add(shift_vars[('S12', 25, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 25, 'night')] == 1)
    model.Add(shift_vars[('S12', 26, 'morning')] == 0)
    model.Add(shift_vars[('S12', 26, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 26, 'night')] == 0)
    model.Add(shift_vars[('S12', 27, 'morning')] == 0)
    model.Add(shift_vars[('S12', 27, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 27, 'night')] == 0)
    model.Add(shift_vars[('S12', 28, 'morning')] == 1)
    model.Add(shift_vars[('S12', 28, 'afternoon')] == 0)
    model.Add(shift_vars[('S12', 28, 'night')] == 0)
    model.Add(shift_vars[('S12', 29, 'morning')] == 0)
    model.Add(shift_vars[('S12', 29, 'afternoon')] == 1)
    model.Add(shift_vars[('S12', 29, 'night')] == 0)
    model.Add(shift_vars[('S12', 30, 'morning')] == 0)
    model.Add(shift_vars[('S12', 30, 'afternoon')] == 1)
    model.Add(shift_vars[('S12', 30, 'night')] == 0)
    model.Add(shift_vars[('P03', 0, 'morning')] == 0)
    model.Add(shift_vars[('P03', 0, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 0, 'night')] == 1)
    model.Add(shift_vars[('P03', 1, 'morning')] == 0)
    model.Add(shift_vars[('P03', 1, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 1, 'night')] == 0)
    model.Add(shift_vars[('P03', 2, 'morning')] == 0)
    model.Add(shift_vars[('P03', 2, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 2, 'night')] == 0)
    model.Add(shift_vars[('P03', 3, 'morning')] == 1)
    model.Add(shift_vars[('P03', 3, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 3, 'night')] == 0)
    model.Add(shift_vars[('P03', 4, 'morning')] == 1)
    model.Add(shift_vars[('P03', 4, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 4, 'night')] == 0)
    model.Add(shift_vars[('P03', 5, 'morning')] == 1)
    model.Add(shift_vars[('P03', 5, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 5, 'night')] == 0)
    model.Add(shift_vars[('P03', 6, 'morning')] == 0)
    model.Add(shift_vars[('P03', 6, 'afternoon')] == 1)
    model.Add(shift_vars[('P03', 6, 'night')] == 0)
    model.Add(shift_vars[('P03', 7, 'morning')] == 0)
    model.Add(shift_vars[('P03', 7, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 7, 'night')] == 1)
    model.Add(shift_vars[('P03', 8, 'morning')] == 0)
    model.Add(shift_vars[('P03', 8, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 8, 'night')] == 0)
    model.Add(shift_vars[('P03', 9, 'morning')] == 0)
    model.Add(shift_vars[('P03', 9, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 9, 'night')] == 0)
    model.Add(shift_vars[('P03', 10, 'morning')] == 0)
    model.Add(shift_vars[('P03', 10, 'afternoon')] == 1)
    model.Add(shift_vars[('P03', 10, 'night')] == 0)
    model.Add(shift_vars[('P03', 11, 'morning')] == 1)
    model.Add(shift_vars[('P03', 11, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 11, 'night')] == 0)
    model.Add(shift_vars[('P03', 12, 'morning')] == 0)
    model.Add(shift_vars[('P03', 12, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 12, 'night')] == 0)
    model.Add(shift_vars[('P03', 13, 'morning')] == 0)
    model.Add(shift_vars[('P03', 13, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 13, 'night')] == 1)
    model.Add(shift_vars[('P03', 14, 'morning')] == 0)
    model.Add(shift_vars[('P03', 14, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 14, 'night')] == 0)
    model.Add(shift_vars[('P03', 15, 'morning')] == 0)
    model.Add(shift_vars[('P03', 15, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 15, 'night')] == 0)
    model.Add(shift_vars[('P03', 16, 'morning')] == 0)
    model.Add(shift_vars[('P03', 16, 'afternoon')] == 1)
    model.Add(shift_vars[('P03', 16, 'night')] == 0)
    model.Add(shift_vars[('P03', 17, 'morning')] == 0)
    model.Add(shift_vars[('P03', 17, 'afternoon')] == 1)
    model.Add(shift_vars[('P03', 17, 'night')] == 0)
    model.Add(shift_vars[('P03', 18, 'morning')] == 0)
    model.Add(shift_vars[('P03', 18, 'afternoon')] == 1)
    model.Add(shift_vars[('P03', 18, 'night')] == 0)
    model.Add(shift_vars[('P03', 19, 'morning')] == 1)
    model.Add(shift_vars[('P03', 19, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 19, 'night')] == 0)
    model.Add(shift_vars[('P03', 20, 'morning')] == 0)
    model.Add(shift_vars[('P03', 20, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 20, 'night')] == 1)
    model.Add(shift_vars[('P03', 21, 'morning')] == 0)
    model.Add(shift_vars[('P03', 21, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 21, 'night')] == 0)
    model.Add(shift_vars[('P03', 22, 'morning')] == 0)
    model.Add(shift_vars[('P03', 22, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 22, 'night')] == 0)
    model.Add(shift_vars[('P03', 23, 'morning')] == 1)
    model.Add(shift_vars[('P03', 23, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 23, 'night')] == 0)
    model.Add(shift_vars[('P03', 24, 'morning')] == 0)
    model.Add(shift_vars[('P03', 24, 'afternoon')] == 1)
    model.Add(shift_vars[('P03', 24, 'night')] == 0)
    model.Add(shift_vars[('P03', 25, 'morning')] == 1)
    model.Add(shift_vars[('P03', 25, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 25, 'night')] == 0)
    model.Add(shift_vars[('P03', 26, 'morning')] == 0)
    model.Add(shift_vars[('P03', 26, 'afternoon')] == 1)
    model.Add(shift_vars[('P03', 26, 'night')] == 0)
    model.Add(shift_vars[('P03', 27, 'morning')] == 0)
    model.Add(shift_vars[('P03', 27, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 27, 'night')] == 1)
    model.Add(shift_vars[('P03', 28, 'morning')] == 0)
    model.Add(shift_vars[('P03', 28, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 28, 'night')] == 0)
    model.Add(shift_vars[('P03', 29, 'morning')] == 0)
    model.Add(shift_vars[('P03', 29, 'afternoon')] == 0)
    model.Add(shift_vars[('P03', 29, 'night')] == 0)
    model.Add(shift_vars[('P03', 30, 'morning')] == 0)
    model.Add(shift_vars[('P03', 30, 'afternoon')] == 1)
    model.Add(shift_vars[('P03', 30, 'night')] == 0)

    model.Minimize(sum(penalty_terms))

    # ========== SOLVE =====================================================
    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = 30
    solver.parameters.log_search_progress = False

    status = solver.Solve(model)

    if status in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        result = {}
        for w in all_workers:
            result[w] = []
            for d in range(n_days):
                for s in shifts:
                    if solver.Value(shift_vars[(w, d, s)]):
                        result[w].append({
                            "day_idx": d,
                            "date": days[d],
                            "shift": s
                        })
        output = {
            "status": "OPTIMAL" if status == cp_model.OPTIMAL else "FEASIBLE",
            "objective": solver.ObjectiveValue(),
            "assignments": result
        }
        print(json.dumps(output))
    else:
        print(json.dumps({
            "status": "INFEASIBLE" if status == cp_model.INFEASIBLE else "UNKNOWN",
            "error": "Nessuna soluzione trovata"
        }))

solve_schedule()
